### ISSUE TITLE
YahooFinance stopped working 5/2025

### ISSUE THREAD

**Issue by codemonkey2k5** [iprak/yahoofinance#161]
It appears that Yahoofinance has made some breaking changes to to their platform.  As such, this plug-in no longer works.

**Comment by iprak** [comment]
What errors are you seeing? I am not seeing any issues at my end. That being said, in the past, requests have failed and then recovered later.

**Comment by wxman60** [comment]
I have the same issue.  All entities became unavailable. Not exactly sure the exact time it happened but it's been like this for a couple of days.

**Comment by kedar-calangutkar** [comment]
+1. Same for me

**Comment by iprak** [comment]
Can you enable debug mode and post relevant log? 

Also do all of you have a small update interval?

**Comment by codemonkey2k5** [comment]
Mine was set to 5 minutes up until the failure, I set it to 2 during troubleshooting.

**Comment by eeztrbo** [comment]
Having the same issue since Tuesday (4/29).  I also have a mini display (GeekMagicCube) that shows stock quotes from yahoo and it doesnt work as well.  Has the API been shut down?

**Comment by iprak** [comment]
It will help if you all can post the error messages from the log.

**Comment by codemonkey2k5** [comment]
Please excuse my ignorance, but where might I find this log?

**Comment by iprak** [comment]
The logs can be found at `Settings > System > Logs`. The `error` level messages should automatically show up. Use `Show raw logs`  to see all of them. Then you can search for `yahoofinance`.

![Image](https://github.com/user-attachments/assets/7e61e06e-ae36-4f00-b045-fa6029ddd646)

**Comment by LiquidPT** [comment]
These are the logs I've been seeing for the last few days:

```
2025-05-01 17:13:02.767 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Crumb request responded with status=429, reason=Too Many Requests
2025-05-01 17:13:02.767 WARNING (MainThread) [custom_components.yahoofinance] Unable to get crumb, re-trying in 60 seconds
```

This repeats over and over again (I would assume about every 60 seconds

**Comment by iprak** [comment]
That seems to be the same observation made in https://github.com/iprak/yahoofinance/issues/125.

The Yahoo end point used is not official but it works.

My suspicion is that the refresh interval being used is aggressive. Given the current market situation, more folks might have been accessing Yahoo data. As such Yahoo might have decided to throttle/ban the request source.

I have been getting data succesfully at my end. I have like 30 symbols at 15 mins refresh rate.

You can try increasing the scan_interval.

If yahoo has blocked requests based on the ip address, then you would have to get a new one. Usually modem/router has an ability to do so. Doing a power cycle on the modem should also get your modem a new public ip address.

**Comment by codemonkey2k5** [comment]
I concur, my log entry says it all. 

![Image](https://github.com/user-attachments/assets/47e25f57-3948-4d50-8291-829da389d6dd)

**Comment by iprak** [comment]
I have also pushed a new release - "This limits crumb retrieval to five attempts, each after a sixty-second delay. After five failures, the retrieval process restarts after five minutes. This might give time to alleviate the 429 return code."

**Comment by LiquidPT** [comment]
mine was always one an hour (3 symbols). So the previous behavior had it hitting the endpoint 60x as much, and even the new behavior is 30x as much as i have configured

**Comment by richardkaufmann** [comment]
Updated to 1.2.17, still getting the "too many requests" error.  Anything left for me to do?

```
This error originated from a custom integration.

Logger: custom_components.yahoofinance.const
Source: custom_components/yahoofinance/__init__.py:238
integration: Yahoo Finance (documentation, issues)
First occurred: 8:29:12 AM (2 occurrences)
Last logged: 8:30:13 AM
```

Unable to get crumb, re-trying in 60 seconds`

Config file:

```
yahoofinance:
  symbols:
    - META
  scan_interval:
    minutes: 10
```

![Image](https://github.com/user-attachments/assets/b741cab7-51cd-4598-bdf1-7489f45d6047)

**Comment by codemonkey2k5** [comment]
I can also add that getting a new external IP did not solve the issue either.  I also flushed the browsers cookies.

**Comment by iprak** [comment]
> I can also add that getting a new external IP did not solve the issue either. I also flushed the browsers cookies.

OK. That was going to be my last suggestion. I did change my settings to use 2min refresh and the requests did not fail.

Final clarification, is the integration within US ? The reason I ask is because requests from Europe go through a GDPR redirection site.

**Comment by iprak** [comment]
I want to add that Yahoo Inc (which is not necessarily Yahoo Finance but maybe the parent umbrella) reports 429 for `Rate Limit exceeded per hour (Limit: 100)` - https://help.yahooinc.com/datax/docs/rate-limits-1

**Comment by codemonkey2k5** [comment]
I am in the US.  I wonder if the fail retry is keeping it violated.   Every time contact fails the error says that it will try again in 60 seconds.

**Comment by iprak** [comment]
> I am in the US. I wonder if the fail retry is keeping it violated. Every time contact fails the error says that it will try again in 60 seconds.

I had the same inkling. So I changed the retry algo to do only 5 tries (with 60 sec wait) and then repeat after 5 mins in v1.2.17.

**Comment by LiquidPT** [comment]
I'm in the US as well.

That retry back off only halves the number of request in an hour (1 per min = 60/hr, 5 per 10 min= 30/hr). By contrast, I normally only check once per hour.

**Comment by outgeeked** [comment]
Just chiming in to report this is also impacting me. Updating to 1.2.17 made no difference, nor did getting a new public IP.

Config:
<img width="157" alt="Image" src="https://github.com/user-attachments/assets/108488fd-4f71-4987-a523-aae6d7b64160" />

Logs:
<img width="821" alt="Image" src="https://github.com/user-attachments/assets/b1fc81ab-cbb5-4eee-8236-a149a643bad8" />

**Comment by iprak** [comment]
This seems to be happening in US-West coast region .. maybe Yahoo data center issue. I can see 429 on West coast but not anywhere else. I have compared the requests made in the two cases but nothing seems to stand out. There has to be something obscure causing this behavior.

**Comment by LiquidPT** [comment]
That tracks for me. I'm in Seattle.

**Comment by outgeeked** [comment]
Agreed, Bay Area.

**Comment by codemonkey2k5** [comment]
Nor Cal.

**Comment by iprak** [comment]
I will continue probing. I VPNed to Seattle and LA where I saw this behavior.

**Comment by eeztrbo** [comment]
Southern Califiornia here. When I use VPN outside of California it works.  I also use a GeekMagic Small TV Pro to display stock quotes and it also uses yahoo finance and only works when VPN outside of the west US.

**Comment by jt6186** [comment]
I'm having the same problem with 10 min request rate for 13 tickers from Arizona.

**Comment by Junikiewicz** [comment]
Same problem in Poland since today around 6:00 CEST.
First error:
`2025-05-06 05:56:39.383 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Error fetching YahooSymbolUpdateCoordinator data: 429, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://quer>`
I have updated the plugin and now i receive 
`2025-05-06 08:49:40.962 ERROR (MainThread) [custom_components.yahoofinance.const] Crumb request responded with status=429, reason=Too Many Requests
`

![Image](https://github.com/user-attachments/assets/f27d4aa4-5c15-49da-a640-6c7c53886a1b)

**Comment by johnstan** [comment]
Also in the Netherlands - hasn't worked for 4 days... 429 error message

**Comment by regevbr** [comment]
Same in Israel :-(

**Comment by iprak** [comment]
What ever change was made at Yahoo end seemed to have been slowly rolled out to servers at other locations.

I might have a tentative solution. Please wait. Do not post additional comments unless you are getting different failure reason.

**Comment by jcarlier** [comment]
i am waiting !!!!!!!!!!   have you a solution ???

**Comment by jcarlier** [comment]
do you know another free provider ?????

**Comment by eddysteurs** [comment]
> do you know another free provider ?????
There is the avanza integration but it does not offer all markets ( eg not uk and Switzerland), but main ones are available

**Comment by copywizard** [comment]
I just installed the latest update 1.2.17 and the addon stopped working before the update everything was a ok

![Image](https://github.com/user-attachments/assets/9b6ac794-4ea6-49e8-8ab7-76c0b86fbf43)

any clue what this could be?

**Comment by iprak** [comment]
> I just installed the latest update 1.2.17 and the addon stopped working before the update everything was a ok
> 
> ![Image](https://github.com/user-attachments/assets/9b6ac794-4ea6-49e8-8ab7-76c0b86fbf43)
> 
> any clue what this could be?
> 
> p.s. 
> 
> indeed also a 429 error but its weird that this happend after the update right? because before that it worked honky dory
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.yahoofinance.const
> Source: custom_components/yahoofinance/coordinator.py:228
> integration: Yahoo Finance (documentation, issues)
> First occurred: 21:18:07 (12 occurrences)
> Last logged: 21:33:09
> 
> Crumb request responded with status=429, reason=Too Many Requests

1.2.17 was an attempt to fix the 429 error. You are encountering the same issue.

**Comment by iprak** [comment]
Please try release 1.2.18.

**Comment by outgeeked** [comment]
Confirmed that 1.2.18 fixed the issue (as seen in Bay Area, California).

Many thanks!

**Comment by LiquidPT** [comment]
Yay, 1.2.18 fixed it for me here in Seattle.

**Comment by codemonkey2k5** [comment]
Fixed for me as well.  Thank you!

**Comment by vanislman** [comment]
Great job, fixed for me too!

**Comment by Jay2645** [comment]
Can also confirm it is fixed! Thank you so much!

**Comment by wxman60** [comment]
1.2.18 fixed the issue for me too. Thanks!

**Comment by Pseudophryne** [comment]
> Please try release 1.2.18.

Legend thank you for the fix 😃

**Comment by copywizard** [comment]
Great work 👍 it is indeed fixed

**Comment by johnstan** [comment]
Brilliant, fixed here too. Thanks so much!
