### ISSUE TITLE
The sensors became unavailable.

### ISSUE THREAD

**Issue by Buakao** [iprak/yahoofinance#70]
Hi,

First of all, Thanks for creating this project. I was able to get it up and running for a month (I think) but as of last week, all the sensor shows unavailable. Any advice is appreciated.

**Comment by iprak** [comment]
The last release was on Dec 25. Can you search for entities with `yahoofinance`? 

Anything interesting in log? You can enable debug logging as following, restart will be requrieduired.
```
logger:
  default: info
  logs:
    custom_components.yahoofinance: debug
```

**Comment by Buakao** [comment]
Thanks for quick reply. I will try debugging and let you know. Btw, it has been unavailable just last 2 days. Jan 26 is the last day that the sensor entities were working.

**Comment by Buakao** [comment]
Here is the error.
This error originated from a custom integration.

Logger: custom_components.yahoofinance.coordinator
Source: custom_components/yahoofinance/coordinator.py:108
Integration: Yahoo Finance (documentation, issues)
First occurred: 7:01:04 AM (134 occurrences)
Last logged: 8:18:19 AM

Error obtaining data, retrying in 20 seconds.

**Comment by iprak** [comment]
There should be some error message logged indicating why the updated failed. When an update failed, the retry is attempted after 20 seconds.

**Comment by iprak** [comment]
I suspect that the request to Yahoo API end point is timing out. If you enable debug logging then that can tell more.

You can change the logger level without restarting from Developer Tools > Services

```
service: logger.set_level
data:
  custom_components.yahoofinance: debug
```

Next invoke service `Yahoo Finance: refresh_symbols` to refresh the data. You should see some log.

**Comment by luizgois-luizalabs** [comment]
These were the logs I got

```
2022-02-03 06:24:44 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Requesting data from 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=MGLU3.SA,LAME4.SA,AMER3.SA,LWSA3.SA,VIIA3.SA,CASH3.SA,MELI34.SA'
2022-02-03 06:24:59 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Timeout fetching YahooSymbolUpdateCoordinator data
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Finished fetching YahooSymbolUpdateCoordinator data in 15.001 seconds (success: False)
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance] Coordinator did not report any data, requesting async_refresh
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Requesting data from 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=MGLU3.SA,LAME4.SA,AMER3.SA,LWSA3.SA,VIIA3.SA,CASH3.SA,MELI34.SA'
2022-02-03 06:24:59 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.yahoofinance
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] Created entity for target_currency=BRL
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] Created entity for target_currency=BRL
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] Created entity for target_currency=BRL
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] Created entity for target_currency=BRL
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] Created entity for target_currency=BRL
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] Created entity for target_currency=BRL
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] Created entity for target_currency=BRL
2022-02-03 06:24:59 INFO (MainThread) [custom_components.yahoofinance.sensor] Entities added for ['MGLU3.SA', 'MELI34.SA', 'AMER3.SA', 'VIIA3.SA', 'LAME4.SA', 'LWSA3.SA', 'CASH3.SA']
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MGLU3.SA Coordinator data is None
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MELI34.SA Coordinator data is None
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] AMER3.SA Coordinator data is None
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] VIIA3.SA Coordinator data is None
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LAME4.SA Coordinator data is None
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LWSA3.SA Coordinator data is None
2022-02-03 06:24:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] CASH3.SA Coordinator data is None
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Finished fetching YahooSymbolUpdateCoordinator data in 15.007 seconds (success: False)
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MGLU3.SA Coordinator data is None
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MELI34.SA Coordinator data is None
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.sensor] AMER3.SA Coordinator data is None
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.sensor] VIIA3.SA Coordinator data is None
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LAME4.SA Coordinator data is None
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LWSA3.SA Coordinator data is None
2022-02-03 06:25:14 DEBUG (MainThread) [custom_components.yahoofinance.sensor] CASH3.SA Coordinator data is None
2022-02-03 06:25:34 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Requesting data from 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=MGLU3.SA,LAME4.SA,AMER3.SA,LWSA3.SA,VIIA3.SA,CASH3.SA,MELI34.SA'
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Finished fetching YahooSymbolUpdateCoordinator data in 15.002 seconds (success: False)
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MGLU3.SA Coordinator data is None
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MELI34.SA Coordinator data is None
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.sensor] AMER3.SA Coordinator data is None
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.sensor] VIIA3.SA Coordinator data is None
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LAME4.SA Coordinator data is None
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LWSA3.SA Coordinator data is None
2022-02-03 06:25:49 DEBUG (MainThread) [custom_components.yahoofinance.sensor] CASH3.SA Coordinator data is None
2022-02-03 06:26:09 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Requesting data from 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=MGLU3.SA,LAME4.SA,AMER3.SA,LWSA3.SA,VIIA3.SA,CASH3.SA,MELI34.SA'
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Finished fetching YahooSymbolUpdateCoordinator data in 15.004 seconds (success: False)
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MGLU3.SA Coordinator data is None
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MELI34.SA Coordinator data is None
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.sensor] AMER3.SA Coordinator data is None
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.sensor] VIIA3.SA Coordinator data is None
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LAME4.SA Coordinator data is None
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LWSA3.SA Coordinator data is None
2022-02-03 06:26:24 DEBUG (MainThread) [custom_components.yahoofinance.sensor] CASH3.SA Coordinator data is None
2022-02-03 06:26:44 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Requesting data from 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=MGLU3.SA,LAME4.SA,AMER3.SA,LWSA3.SA,VIIA3.SA,CASH3.SA,MELI34.SA'
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Finished fetching YahooSymbolUpdateCoordinator data in 15.013 seconds (success: False)
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MGLU3.SA Coordinator data is None
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MELI34.SA Coordinator data is None
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] AMER3.SA Coordinator data is None
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] VIIA3.SA Coordinator data is None
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LAME4.SA Coordinator data is None
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LWSA3.SA Coordinator data is None
2022-02-03 06:26:59 DEBUG (MainThread) [custom_components.yahoofinance.sensor] CASH3.SA Coordinator data is None
2022-02-03 06:27:19 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Requesting data from 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=MGLU3.SA,LAME4.SA,AMER3.SA,LWSA3.SA,VIIA3.SA,CASH3.SA,MELI34.SA'
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Finished fetching YahooSymbolUpdateCoordinator data in 15.002 seconds (success: False)
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MGLU3.SA Coordinator data is None
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.sensor] MELI34.SA Coordinator data is None
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.sensor] AMER3.SA Coordinator data is None
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.sensor] VIIA3.SA Coordinator data is None
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LAME4.SA Coordinator data is None
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.sensor] LWSA3.SA Coordinator data is None
2022-02-03 06:27:34 DEBUG (MainThread) [custom_components.yahoofinance.sensor] CASH3.SA Coordinator data is None
```

**Comment by iprak** [comment]
As per the logs, the request `https://query1.finance.yahoo.com/v7/finance/quote?symbols=MGLU3.SA,LAME4.SA,AMER3.SA,LWSA3.SA,VIIA3.SA,CASH3.SA,MELI34.SA` is not returning any data in 15 seconds. 15 seconds is a long time. I tried the same and got response back in a second. 

I can't say why is preventing the access in your case. Can you navigate to that url successfully in browser? Did you define any `scan_interval` under yahoofinance ?

**Comment by luizgois-luizalabs** [comment]
I can easily access the address in the browser.
I added:

```
   scan_interval:
     hours: 1
```

**Comment by iprak** [comment]
Could the url be somehow blocked? The only thing I can think of is to add some more logging to see what is response code.

**Comment by luizgois-luizalabs** [comment]
I reinstalled via hacs and it worked again

**Comment by iprak** [comment]
Ok. I had not released anything yet so this might be due to some install issue.

@Buakao What version are you at? What kind of HA install was it?

**Comment by luizgois-luizalabs** [comment]
It has become unavailable again

**Comment by iprak** [comment]
I have pushed out a new release with more logging in the area when request is made.

**Comment by luizgois-luizalabs** [comment]
I updated the version with more logs and returned the log below:
```
2022-02-04 06:31:40 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Timed out getting data from https://query1.finance.yahoo.com/v7/finance/quote?symbols=LWSA3.SA,MGLU3.SA,VIIA3.SA,MELI34.SA,CASH3.SA,AMER3.SA
```

**Comment by iprak** [comment]
That confirms the request to https://query1.finance.yahoo.com/v7/finance/quote?symbols=LWSA3.SA,MGLU3.SA,VIIA3.SA,MELI34.SA,CASH3.SA,AMER3.SA is not returning any data in 15 seconds but I don't know why.

**Comment by iprak** [comment]
How is your HA installed? I can try to replicate the setup.

**Comment by luizgois-luizalabs** [comment]
I'm running with VirtualBox, with the image available on the HomeAssistant website. I'm running with the latest version, but even before the update it wasn't working, but it worked for a long time with this installation.

**Comment by luizgois-luizalabs** [comment]
It's working now.
Could it be some limitation on the amount of API requests?

**Comment by iprak** [comment]
That is possible. The yahoo web end point is undocumented which is why I limited the minimum refresh interval. But you were able to successfully navigate to yahoo query url. One thing could be that the response is being limited based on request headers which I will look into more. I have been using 6hr without any issues for a very long time. See if increasing interval to 3 or 4 hr helps.

**Comment by luizgois-luizalabs** [comment]
Okay, I left the break at 3 hours, I'll follow up over the weekend and let you know the result.

Is there any debug I can do? I know python, but I didn't get to develop or debug something with HomeAssistant

**Comment by iprak** [comment]
Yes that will be awesome. The method in question is `get_json` in yahoofinance/coordinator.py makes a get request on an aiohttp object.

**Comment by iprak** [comment]
So I created a VirtualBox instance with only yahoofinance sensors with 60 second refresh and everything was fine. Could there something in your network adapter settings preventing requests going out?

**Comment by leogaggl** [comment]
I also can't get this to work.

Standard HA Docker install with Home Assistant 2022.2.6
HACS install of the integration

**Comment by Buakao** [comment]
Well, sorry that I haven't checked this thread for a long while. I solve the issue by switching to another HA in another machine in another location. The new machine is rpi 4b 8Gb, runing HASS.io installing as a docker (the one with the issue running HassOS on dedicated pi4b, 4Gb). Since then I have no issue, which explains why I have been vanish, sorry. I hope this info help with others. I haven't tried reinstall yahoo finance on the first machine.

**Comment by leogaggl** [comment]
Running https://hub.docker.com/r/homeassistant/home-assistant I can not get this integration to work

The following integrations and platforms could not be set up:

yahoofinance
yahoofinance.sensor

Please check your config and logs

Nothing reported in logs.

**Comment by iprak** [comment]
> I also can't get this to work.
> 
> Standard HA Docker install with Home Assistant 2022.2.6 HACS install of the integration

Are you seeing sensors being unavailable? If so then debug logging might help discover what is going on.

**Comment by iprak** [comment]
The files seem right. Can you maybe enable debug logging at default level? 

```
logger:
  default: debug
```

Also just to be clear the files are directly in the folder `config\custom_components\yahoofinance` and not in a sub-folder?

**Comment by leogaggl** [comment]
Files are definitely in the correct folder

ls /docker/homeassistant/config/custom_components/yahoofinance/
const.py	__init__.py    __pycache__  services.yaml
coordinator.py	manifest.json  sensor.py

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/yahoofinance/__init__.py:138
Integration: yahoofinance (documentation, issues)
First occurred: 9:55:10 AM (1 occurrences)
Last logged: 9:55:10 AM

Error during setup of component yahoofinance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/config/custom_components/yahoofinance/__init__.py", line 173, in async_setup
    scan_interval = parse_scan_interval(domain_config.get(CONF_SCAN_INTERVAL))
  File "/config/custom_components/yahoofinance/__init__.py", line 138, in parse_scan_interval
    elif scan_interval < MINIMUM_SCAN_INTERVAL:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'

**Comment by iprak** [comment]
> 

Can you share your yahoofinance configuration?

**Comment by leogaggl** [comment]
- platform: yahoofinance
  show_trending_icon: true
  scan_interval:
    hours: 4
  symbols:
    - EURAUD=X


I am only interested in currency symbols. Have opened another issue related to that. Seems that the plugin does not support cryptocurrencies (which are supported by YahooFinance though)

**Comment by iprak** [comment]
Your declaration is incorrect, please refer to the examples in [Configuration](https://github.com/iprak/yahoofinance) .

**Comment by leogaggl** [comment]
Which part of the Declaration?

**Comment by iprak** [comment]
> platform: yahoofinance
> show_trending_icon: true
> scan_interval:
> hours: 4
> symbols:
> * EURAUD=X

The declaration should be something like this

```
yahoofinance:
    show_trending_icon: true
    scan_interval:
        hours: 4
    symbols:
        - EURAUD=X
```

**Comment by leogaggl** [comment]
I can not get this to work with any symbols that I am interested. But also with your sample symbol

```
### sensors.yaml
#
- platform: yahoofinance
  show_trending_icon: true
  scan_interval:
    hours: 4
  symbols:
    - ISTNX
```

Error during setup of component yahoofinance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/config/custom_components/yahoofinance/__init__.py", line 173, in async_setup
    scan_interval = parse_scan_interval(domain_config.get(CONF_SCAN_INTERVAL))
  File "/config/custom_components/yahoofinance/__init__.py", line 138, in parse_scan_interval
    elif scan_interval < MINIMUM_SCAN_INTERVAL:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'

**Comment by iprak** [comment]
Your declaration is incorrect, it has to be under yahoofinance as

```
yahoofinance:
```

and not using platform.

**Comment by iprak** [comment]
@leogaggl Did you get it working?

**Comment by leogaggl** [comment]
Hi @iprak - been travelling for a few days. 

But yes - had to get this declaration out of sensors.yaml into the main config file.

Thanks for your assistance

**Comment by iprak** [comment]
There seems to be 2 issues being discussed in this thread.

One was due to mis configuration and has been confirmed as resolved by @leogaggl.

The second seems to be due to a short update duration. It is possible that Yahoo server is not responding in that case. The web end points are not documented so I would go with a longer duration. The default `scan_interval` is 6 hours. @luizgois-luizalabs was able to resolve the missing data by increasing the interval to 1 hr.

**Comment by shahram7** [comment]
Hello all,
I have the same problem since last Friday I think. Suddenly all my sensors get unavailable. I tried using the scan_interval but they are still not available. 
Best regards
```
yahoofinance:
  show_trending_icon: true
  scan_interval:
    hours: 1
  symbols:
    - BTC-EUR
    - ETH-EUR
    - DOGE-EUR
    - symbol: AMZN
      target_currency: EUR
```

**Comment by iprak** [comment]
@shahram7 Mostly likely your issue was the same as #96 and should have been resolved with latest updates.

**Comment by iprak** [comment]
This issue should have been resolved.
